-- BrightHut database schema (PostgreSQL)
-- Source: Appendix A - Data Dictionary (17 tables)
--
-- Notes:
-- - Uses CHECK constraints for the “One of …” fields (instead of PostgreSQL enums) to keep migrations simple.
-- - Uses timestamptz for “datetime”.
-- - Uses generated identity for primary keys (works well for Azure Database for PostgreSQL).

BEGIN;

CREATE SCHEMA IF NOT EXISTS brighthut;
SET search_path = brighthut;

-- ---------- Core reference tables ----------

CREATE TABLE IF NOT EXISTS safehouses (
  safehouse_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  safehouse_code text NOT NULL,
  name text NOT NULL,
  region text NOT NULL,
  city text NOT NULL,
  province text NOT NULL,
  country text NOT NULL DEFAULT 'Philippines',
  open_date date,
  status text NOT NULL,
  capacity_girls integer,
  capacity_staff integer,
  current_occupancy integer,
  notes text,
  CONSTRAINT safehouses_region_chk CHECK (region IN ('Luzon','Visayas','Mindanao')),
  CONSTRAINT safehouses_status_chk CHECK (status IN ('Active','Inactive')),
  CONSTRAINT safehouses_code_uk UNIQUE (safehouse_code)
);

CREATE TABLE IF NOT EXISTS partners (
  partner_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_name text NOT NULL,
  partner_type text NOT NULL,
  role_type text NOT NULL,
  contact_name text,
  email text,
  phone text,
  region text,
  status text NOT NULL,
  start_date date,
  end_date date,
  notes text,
  CONSTRAINT partners_partner_type_chk CHECK (partner_type IN ('Organization','Individual')),
  CONSTRAINT partners_role_type_chk CHECK (role_type IN ('Education','Evaluation','SafehouseOps','FindSafehouse','Logistics','Transport','Maintenance')),
  CONSTRAINT partners_status_chk CHECK (status IN ('Active','Inactive'))
);

CREATE TABLE IF NOT EXISTS partner_assignments (
  assignment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id integer NOT NULL REFERENCES partners(partner_id),
  safehouse_id integer REFERENCES safehouses(safehouse_id),
  program_area text NOT NULL,
  assignment_start date,
  assignment_end date,
  responsibility_notes text,
  is_primary boolean NOT NULL DEFAULT false,
  status text NOT NULL,
  CONSTRAINT partner_assignments_program_area_chk CHECK (program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance')),
  CONSTRAINT partner_assignments_status_chk CHECK (status IN ('Active','Ended'))
);

CREATE TABLE IF NOT EXISTS supporters (
  supporter_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supporter_type text NOT NULL,
  display_name text NOT NULL,
  organization_name text,
  first_name text,
  last_name text,
  relationship_type text NOT NULL,
  region text,
  country text,
  email text,
  phone text,
  status text NOT NULL,
  first_donation_date date,
  acquisition_channel text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT supporters_supporter_type_chk CHECK (supporter_type IN ('MonetaryDonor','InKindDonor','Volunteer','SkillsContributor','SocialMediaAdvocate','PartnerOrganization')),
  CONSTRAINT supporters_relationship_type_chk CHECK (relationship_type IN ('Local','International','PartnerOrganization')),
  CONSTRAINT supporters_status_chk CHECK (status IN ('Active','Inactive')),
  CONSTRAINT supporters_acquisition_channel_chk CHECK (acquisition_channel IS NULL OR acquisition_channel IN ('Website','SocialMedia','Event','WordOfMouth','PartnerReferral','Church'))
);

-- ---------- Social / donation tables ----------

CREATE TABLE IF NOT EXISTS social_media_posts (
  post_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform text NOT NULL,
  platform_post_id text NOT NULL,
  post_url text,
  created_at timestamptz NOT NULL,
  day_of_week text NOT NULL,
  post_hour integer NOT NULL,
  post_type text NOT NULL,
  media_type text NOT NULL,
  caption text,
  hashtags text,
  num_hashtags integer,
  mentions_count integer,
  has_call_to_action boolean NOT NULL DEFAULT false,
  call_to_action_type text,
  content_topic text NOT NULL,
  sentiment_tone text NOT NULL,
  caption_length integer,
  features_resident_story boolean NOT NULL DEFAULT false,
  campaign_name text,
  is_boosted boolean NOT NULL DEFAULT false,
  boost_budget_php numeric(14,2),
  impressions integer,
  reach integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  click_throughs integer,
  video_views integer,
  engagement_rate numeric(10,6),
  profile_visits integer,
  donation_referrals integer,
  estimated_donation_value_php numeric(14,2),
  follower_count_at_post integer,
  watch_time_seconds integer,
  avg_view_duration_seconds integer,
  subscriber_count_at_post integer,
  forwards integer,
  CONSTRAINT social_media_posts_platform_chk CHECK (platform IN ('Facebook','Instagram','Twitter','TikTok','LinkedIn','YouTube','WhatsApp')),
  CONSTRAINT social_media_posts_post_hour_chk CHECK (post_hour BETWEEN 0 AND 23),
  CONSTRAINT social_media_posts_post_type_chk CHECK (post_type IN ('ImpactStory','Campaign','EventPromotion','ThankYou','EducationalContent','FundraisingAppeal')),
  CONSTRAINT social_media_posts_media_type_chk CHECK (media_type IN ('Photo','Video','Carousel','Text','Reel')),
  CONSTRAINT social_media_posts_call_to_action_type_chk CHECK (call_to_action_type IS NULL OR call_to_action_type IN ('DonateNow','LearnMore','ShareStory','SignUp')),
  CONSTRAINT social_media_posts_content_topic_chk CHECK (content_topic IN ('Education','Health','Reintegration','DonorImpact','SafehouseLife','EventRecap','CampaignLaunch','Gratitude','AwarenessRaising')),
  CONSTRAINT social_media_posts_sentiment_tone_chk CHECK (sentiment_tone IN ('Hopeful','Urgent','Celebratory','Informative','Grateful','Emotional')),
  CONSTRAINT social_media_posts_platform_post_uk UNIQUE (platform, platform_post_id)
);

CREATE TABLE IF NOT EXISTS donations (
  donation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supporter_id integer NOT NULL REFERENCES supporters(supporter_id),
  donation_type text NOT NULL,
  donation_date date NOT NULL,
  channel_source text NOT NULL,
  currency_code text,
  amount numeric(14,2),
  estimated_value numeric(14,2),
  impact_unit text NOT NULL,
  is_recurring boolean NOT NULL DEFAULT false,
  campaign_name text,
  notes text,
  created_by_partner_id integer REFERENCES partners(partner_id),
  referral_post_id integer REFERENCES social_media_posts(post_id),
  CONSTRAINT donations_donation_type_chk CHECK (donation_type IN ('Monetary','InKind','Time','Skills','SocialMedia')),
  CONSTRAINT donations_channel_source_chk CHECK (channel_source IN ('Campaign','Event','Direct','SocialMedia','PartnerReferral')),
  CONSTRAINT donations_impact_unit_chk CHECK (impact_unit IN ('pesos','items','hours','campaigns'))
);

CREATE TABLE IF NOT EXISTS in_kind_donation_items (
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donation_id integer NOT NULL REFERENCES donations(donation_id) ON DELETE CASCADE,
  item_name text NOT NULL,
  item_category text NOT NULL,
  quantity integer NOT NULL,
  unit_of_measure text NOT NULL,
  estimated_unit_value numeric(14,2),
  intended_use text NOT NULL,
  received_condition text NOT NULL,
  CONSTRAINT in_kind_item_category_chk CHECK (item_category IN ('Food','Supplies','Clothing','SchoolMaterials','Hygiene','Furniture','Medical')),
  CONSTRAINT in_kind_uom_chk CHECK (unit_of_measure IN ('pcs','boxes','kg','sets','packs')),
  CONSTRAINT in_kind_intended_use_chk CHECK (intended_use IN ('Meals','Education','Shelter','Hygiene','Health')),
  CONSTRAINT in_kind_received_condition_chk CHECK (received_condition IN ('New','Good','Fair'))
);

CREATE TABLE IF NOT EXISTS donation_allocations (
  allocation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donation_id integer NOT NULL REFERENCES donations(donation_id) ON DELETE CASCADE,
  safehouse_id integer NOT NULL REFERENCES safehouses(safehouse_id),
  program_area text NOT NULL,
  amount_allocated numeric(14,2) NOT NULL,
  allocation_date date,
  allocation_notes text,
  CONSTRAINT donation_allocations_program_area_chk CHECK (program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance','Outreach'))
);

-- ---------- Resident / case tables ----------

CREATE TABLE IF NOT EXISTS residents (
  resident_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_control_no text NOT NULL,
  internal_code text NOT NULL,
  safehouse_id integer NOT NULL REFERENCES safehouses(safehouse_id),
  case_status text NOT NULL,
  sex text NOT NULL,
  date_of_birth date,
  birth_status text,
  place_of_birth text,
  religion text,
  case_category text NOT NULL,
  sub_cat_orphaned boolean NOT NULL DEFAULT false,
  sub_cat_trafficked boolean NOT NULL DEFAULT false,
  sub_cat_child_labor boolean NOT NULL DEFAULT false,
  sub_cat_physical_abuse boolean NOT NULL DEFAULT false,
  sub_cat_sexual_abuse boolean NOT NULL DEFAULT false,
  sub_cat_osaec boolean NOT NULL DEFAULT false,
  sub_cat_cicl boolean NOT NULL DEFAULT false,
  sub_cat_at_risk boolean NOT NULL DEFAULT false,
  sub_cat_street_child boolean NOT NULL DEFAULT false,
  sub_cat_child_with_hiv boolean NOT NULL DEFAULT false,
  is_pwd boolean NOT NULL DEFAULT false,
  pwd_type text,
  has_special_needs boolean NOT NULL DEFAULT false,
  special_needs_diagnosis text,
  family_is_4ps boolean NOT NULL DEFAULT false,
  family_solo_parent boolean NOT NULL DEFAULT false,
  family_indigenous boolean NOT NULL DEFAULT false,
  family_parent_pwd boolean NOT NULL DEFAULT false,
  family_informal_settler boolean NOT NULL DEFAULT false,
  date_of_admission date,
  age_upon_admission text,
  present_age text,
  length_of_stay text,
  referral_source text,
  referring_agency_person text,
  date_colb_registered date,
  date_colb_obtained date,
  assigned_social_worker text,
  initial_case_assessment text,
  date_case_study_prepared date,
  reintegration_type text,
  reintegration_status text,
  initial_risk_level text,
  current_risk_level text,
  date_enrolled date,
  date_closed date,
  created_at timestamptz NOT NULL DEFAULT now(),
  notes_restricted text,
  CONSTRAINT residents_case_status_chk CHECK (case_status IN ('Active','Closed','Transferred')),
  CONSTRAINT residents_sex_chk CHECK (sex IN ('F')),
  CONSTRAINT residents_birth_status_chk CHECK (birth_status IS NULL OR birth_status IN ('Marital','Non-Marital')),
  CONSTRAINT residents_case_category_chk CHECK (case_category IN ('Abandoned','Foundling','Surrendered','Neglected')),
  CONSTRAINT residents_referral_source_chk CHECK (referral_source IS NULL OR referral_source IN ('Government Agency','NGO','Police','Self-Referral','Community','Court Order')),
  CONSTRAINT residents_reintegration_type_chk CHECK (reintegration_type IS NULL OR reintegration_type IN ('Family Reunification','Foster Care','Adoption (Domestic)','Adoption (Inter-Country)','Independent Living','None')),
  CONSTRAINT residents_reintegration_status_chk CHECK (reintegration_status IS NULL OR reintegration_status IN ('Not Started','In Progress','Completed','On Hold')),
  CONSTRAINT residents_risk_level_chk CHECK (
    (initial_risk_level IS NULL OR initial_risk_level IN ('Low','Medium','High','Critical'))
    AND
    (current_risk_level IS NULL OR current_risk_level IN ('Low','Medium','High','Critical'))
  ),
  CONSTRAINT residents_case_control_uk UNIQUE (case_control_no),
  CONSTRAINT residents_internal_code_uk UNIQUE (internal_code)
);

CREATE TABLE IF NOT EXISTS process_recordings (
  recording_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  session_date date NOT NULL,
  social_worker text,
  session_type text NOT NULL,
  session_duration_minutes integer,
  emotional_state_observed text,
  emotional_state_end text,
  session_narrative text,
  interventions_applied text,
  follow_up_actions text,
  progress_noted boolean NOT NULL DEFAULT false,
  concerns_flagged boolean NOT NULL DEFAULT false,
  referral_made boolean NOT NULL DEFAULT false,
  notes_restricted text,
  CONSTRAINT process_recordings_session_type_chk CHECK (session_type IN ('Individual','Group')),
  CONSTRAINT process_recordings_emotional_state_obs_chk CHECK (emotional_state_observed IS NULL OR emotional_state_observed IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed')),
  CONSTRAINT process_recordings_emotional_state_end_chk CHECK (emotional_state_end IS NULL OR emotional_state_end IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed'))
);

CREATE TABLE IF NOT EXISTS home_visitations (
  visitation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  visit_date date NOT NULL,
  social_worker text,
  visit_type text NOT NULL,
  location_visited text,
  family_members_present text,
  purpose text,
  observations text,
  family_cooperation_level text,
  safety_concerns_noted boolean NOT NULL DEFAULT false,
  follow_up_needed boolean NOT NULL DEFAULT false,
  follow_up_notes text,
  visit_outcome text,
  CONSTRAINT home_visitations_visit_type_chk CHECK (visit_type IN ('Initial Assessment','Routine Follow-Up','Reintegration Assessment','Post-Placement Monitoring','Emergency')),
  CONSTRAINT home_visitations_family_coop_chk CHECK (family_cooperation_level IS NULL OR family_cooperation_level IN ('Highly Cooperative','Cooperative','Neutral','Uncooperative')),
  CONSTRAINT home_visitations_visit_outcome_chk CHECK (visit_outcome IS NULL OR visit_outcome IN ('Favorable','Needs Improvement','Unfavorable','Inconclusive'))
);

CREATE TABLE IF NOT EXISTS education_records (
  education_record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  record_date date NOT NULL,
  program_name text NOT NULL,
  course_name text NOT NULL,
  education_level text NOT NULL,
  attendance_status text NOT NULL,
  attendance_rate numeric(5,4),
  progress_percent numeric(6,2),
  completion_status text NOT NULL,
  gpa_like_score numeric(4,2),
  notes text,
  CONSTRAINT education_program_chk CHECK (program_name IN ('Bridge Program','Secondary Support','Vocational Skills','Literacy Boost')),
  CONSTRAINT education_course_chk CHECK (course_name IN ('Math','English','Science','Life Skills','Computer Basics','Livelihood')),
  CONSTRAINT education_level_chk CHECK (education_level IN ('Primary','Secondary','Vocational','CollegePrep')),
  CONSTRAINT education_attendance_chk CHECK (attendance_status IN ('Present','Late','Absent')),
  CONSTRAINT education_completion_chk CHECK (completion_status IN ('NotStarted','InProgress','Completed'))
);

CREATE TABLE IF NOT EXISTS health_wellbeing_records (
  health_record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  record_date date NOT NULL,
  weight_kg numeric(6,2),
  height_cm numeric(6,2),
  bmi numeric(6,2),
  nutrition_score numeric(4,2),
  sleep_score numeric(4,2),
  energy_score numeric(4,2),
  general_health_score numeric(4,2),
  medical_checkup_done boolean NOT NULL DEFAULT false,
  dental_checkup_done boolean NOT NULL DEFAULT false,
  psychological_checkup_done boolean NOT NULL DEFAULT false,
  medical_notes_restricted text
);

CREATE TABLE IF NOT EXISTS intervention_plans (
  plan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  plan_category text NOT NULL,
  plan_description text NOT NULL,
  services_provided text,
  target_value numeric(14,2),
  target_date date,
  status text NOT NULL,
  case_conference_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT intervention_plans_category_chk CHECK (plan_category IN ('Safety','Psychosocial','Education','Physical Health','Legal','Reintegration')),
  CONSTRAINT intervention_plans_status_chk CHECK (status IN ('Open','In Progress','Achieved','On Hold','Closed'))
);

CREATE TABLE IF NOT EXISTS incident_reports (
  incident_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id integer NOT NULL REFERENCES residents(resident_id) ON DELETE CASCADE,
  safehouse_id integer NOT NULL REFERENCES safehouses(safehouse_id),
  incident_date date NOT NULL,
  incident_type text NOT NULL,
  severity text NOT NULL,
  description text,
  response_taken text,
  resolved boolean NOT NULL DEFAULT false,
  resolution_date date,
  reported_by text,
  follow_up_required boolean NOT NULL DEFAULT false,
  CONSTRAINT incident_reports_type_chk CHECK (incident_type IN ('Behavioral','Medical','Security','RunawayAttempt','SelfHarm','ConflictWithPeer','PropertyDamage')),
  CONSTRAINT incident_reports_severity_chk CHECK (severity IN ('Low','Medium','High'))
);

-- ---------- Aggregates / snapshots ----------

CREATE TABLE IF NOT EXISTS safehouse_monthly_metrics (
  metric_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  safehouse_id integer NOT NULL REFERENCES safehouses(safehouse_id),
  month_start date NOT NULL,
  month_end date NOT NULL,
  active_residents integer,
  avg_education_progress numeric(6,2),
  avg_health_score numeric(4,2),
  process_recording_count integer,
  home_visitation_count integer,
  incident_count integer,
  notes text,
  CONSTRAINT safehouse_monthly_metrics_month_uk UNIQUE (safehouse_id, month_start)
);

CREATE TABLE IF NOT EXISTS public_impact_snapshots (
  snapshot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_date date NOT NULL,
  headline text,
  summary_text text,
  metric_payload_json text,
  is_published boolean NOT NULL DEFAULT false,
  published_at date,
  CONSTRAINT public_impact_snapshots_month_uk UNIQUE (snapshot_date)
);

-- Helpful indexes for common joins
CREATE INDEX IF NOT EXISTS idx_partner_assignments_partner_id ON partner_assignments(partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_assignments_safehouse_id ON partner_assignments(safehouse_id);
CREATE INDEX IF NOT EXISTS idx_donations_supporter_id ON donations(supporter_id);
CREATE INDEX IF NOT EXISTS idx_donations_referral_post_id ON donations(referral_post_id);
CREATE INDEX IF NOT EXISTS idx_in_kind_donation_items_donation_id ON in_kind_donation_items(donation_id);
CREATE INDEX IF NOT EXISTS idx_donation_allocations_donation_id ON donation_allocations(donation_id);
CREATE INDEX IF NOT EXISTS idx_donation_allocations_safehouse_id ON donation_allocations(safehouse_id);
CREATE INDEX IF NOT EXISTS idx_residents_safehouse_id ON residents(safehouse_id);
CREATE INDEX IF NOT EXISTS idx_process_recordings_resident_id ON process_recordings(resident_id);
CREATE INDEX IF NOT EXISTS idx_home_visitations_resident_id ON home_visitations(resident_id);
CREATE INDEX IF NOT EXISTS idx_education_records_resident_id ON education_records(resident_id);
CREATE INDEX IF NOT EXISTS idx_health_records_resident_id ON health_wellbeing_records(resident_id);
CREATE INDEX IF NOT EXISTS idx_intervention_plans_resident_id ON intervention_plans(resident_id);
CREATE INDEX IF NOT EXISTS idx_incident_reports_resident_id ON incident_reports(resident_id);
CREATE INDEX IF NOT EXISTS idx_incident_reports_safehouse_id ON incident_reports(safehouse_id);
CREATE INDEX IF NOT EXISTS idx_safehouse_monthly_metrics_safehouse_id ON safehouse_monthly_metrics(safehouse_id);

COMMIT;

